# Generated by Django 4.1.7 on 2023-03-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser", old_name="is_guest", new_name="is_adult",
        ),
    ]
