# Generated by Django 4.1.7 on 2023-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_is_guest_customuser_is_adult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_adult",
            field=models.BooleanField(default=False),
        ),
    ]
