# Generated by Django 4.1.7 on 2023-03-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comment_article"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="commentor",),
    ]
