# Generated by Django 4.1.7 on 2023-03-11 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0006_alter_comment_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                db_column="article_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="creator",
            field=models.ForeignKey(
                db_column="creator_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
