# Generated by Django 4.1.7 on 2023-03-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
        ("comments", "0008_remove_comment_article"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="creator",),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                db_column="article_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="article.article",
            ),
        ),
    ]
