# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0001_initial"),
        ("comments", "0009_remove_comment_creator_comment_article"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="parent",),
        migrations.AddField(
            model_name="comment",
            name="creator",
            field=models.ForeignKey(
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                db_column="article_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="article.article",
            ),
        ),
    ]
