# Generated by Django 4.1.7 on 2023-03-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0010_remove_comment_parent_comment_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comments.comment",
            ),
        ),
    ]
